"""Word timings -> styled ASS with per-word karaoke timing.

The **sweep** preset (classic ``\\kf`` wipe) is fully implemented and is what
libass animates reliably — validate output in mpv before Kdenlive (PLAN Phase 2).
The **pop** preset (only the current word highlighted, others reverting) needs
per-word ``\\t`` colour transforms or one event per word window; it is a Phase 2
TODO and raises ``NotImplementedError`` rather than emitting wrong-looking output.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class KaraokePreset(str, Enum):
    SWEEP = "sweep"   # classic fill/wipe over the active word
    POP = "pop"       # per-word colour switch (Phase 2)


@dataclass(frozen=True, slots=True)
class Word:
    text: str
    start: float  # seconds
    end: float    # seconds

    @property
    def duration(self) -> float:
        return max(0.0, self.end - self.start)


def ass_timestamp(seconds: float) -> str:
    """Seconds -> ASS ``H:MM:SS.cs`` (centisecond precision)."""
    if seconds < 0:
        seconds = 0.0
    total_cs = round(seconds * 100)
    cs = total_cs % 100
    total_s = total_cs // 100
    s = total_s % 60
    m = (total_s // 60) % 60
    h = total_s // 3600
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _cs(duration_seconds: float) -> int:
    """Duration in centiseconds, the unit ASS ``\\k``/``\\kf`` expects. Min 1."""
    return max(1, round(duration_seconds * 100))


def group_lines(
    words: list[Word],
    max_chars: int = 32,
    max_words: int = 7,
) -> list[list[Word]]:
    """Group words into caption lines, mirroring subtitle line-break behaviour.

    Breaks when adding the next word would exceed ``max_chars`` or ``max_words``.
    """
    lines: list[list[Word]] = []
    current: list[Word] = []
    char_count = 0
    for w in words:
        added = len(w.text) + (1 if current else 0)
        if current and (len(current) >= max_words or char_count + added > max_chars):
            lines.append(current)
            current, char_count = [], 0
            added = len(w.text)
        current.append(w)
        char_count += added
    if current:
        lines.append(current)
    return lines


def _sweep_line_text(line: list[Word]) -> str:
    """Emit the ``{\\kf<cs>}word`` run for one line.

    Gaps between consecutive words become a ``\\k`` hold on the joining space so
    the wipe timing stays locked to the audio.
    """
    parts: list[str] = []
    for i, w in enumerate(line):
        if i > 0:
            gap = line[i].start - line[i - 1].end
            if gap > 0.02:
                parts.append(f"{{\\k{_cs(gap)}}} ")
            else:
                parts.append(" ")
        parts.append(f"{{\\kf{_cs(w.duration)}}}{w.text}")
    return "".join(parts)


def generate_ass(
    words: list[Word],
    style=None,
    preset: KaraokePreset | str = KaraokePreset.SWEEP,
    *,
    play_res: tuple[int, int] = (1920, 1080),
    max_chars: int = 32,
    max_words: int = 7,
) -> str:
    """Render word timings to a complete ASS document string."""
    from ..styles import NULDRUMS  # local import keeps core import-light

    style = style or NULDRUMS
    preset = KaraokePreset(preset)
    if preset is KaraokePreset.POP:
        raise NotImplementedError(
            "pop preset (single-word highlight) is Phase 2 — use SWEEP for now"
        )

    width, height = play_res
    head = [
        "[Script Info]",
        "; Generated by NulCaption",
        "ScriptType: v4.00+",
        f"PlayResX: {width}",
        f"PlayResY: {height}",
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        style.format_line(),
        style.to_ass_style_line(),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, "
        "MarginV, Effect, Text",
    ]

    events: list[str] = []
    for line in group_lines(words, max_chars=max_chars, max_words=max_words):
        if not line:
            continue
        start = ass_timestamp(line[0].start)
        end = ass_timestamp(line[-1].end)
        text = _sweep_line_text(line)
        events.append(
            f"Dialogue: 0,{start},{end},{style.name},,0,0,0,,{text}"
        )

    return "\n".join(head + events) + "\n"
